"""
Celestia — AI Astrology Web App
Flask backend | No API keys required
"""
from flask import Flask, render_template, request, jsonify, Response
from astrology.calculator import calculate_chart
from astrology.interpretations import generate_reading
from io import BytesIO
import json
import re

app = Flask(__name__)
app.secret_key = "celestia-astro-2024-secret"


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/reading", methods=["POST"])
def reading():
    name = request.form.get("name", "").strip()
    dob = request.form.get("dob", "").strip()
    birth_time = request.form.get("birth_time", "").strip()
    birth_place = request.form.get("birth_place", "").strip()

    # Validation
    errors = []
    if not name:
        errors.append("Full name is required.")
    if not dob:
        errors.append("Date of birth is required.")
    if not birth_time:
        errors.append("Birth time is required.")
    if not birth_place:
        errors.append("Birth place is required.")

    if errors:
        return render_template("index.html", errors=errors,
                               form_data=request.form)

    # Calculate chart
    chart_data = calculate_chart(name, dob, birth_time, birth_place)

    if not chart_data.get("success"):
        error_msg = chart_data.get("error", "Unknown error occurred.")
        return render_template("index.html", errors=[error_msg],
                               form_data=request.form)

    # Generate reading
    reading_data = generate_reading(chart_data)

    # Merge chart + reading for template
    context = {**chart_data, **reading_data}
    return render_template("reading.html", **context)


@app.route("/api/chart", methods=["POST"])
def api_chart():
    """JSON API endpoint for chart data."""
    data = request.get_json() or {}
    name = data.get("name", "").strip()
    dob = data.get("dob", "").strip()
    birth_time = data.get("birth_time", "").strip()
    birth_place = data.get("birth_place", "").strip()

    chart_data = calculate_chart(name, dob, birth_time, birth_place)
    if not chart_data.get("success"):
        return jsonify({"error": chart_data.get("error")}), 400

    reading_data = generate_reading(chart_data)
    return jsonify({**chart_data, **reading_data})


@app.route("/export/text", methods=["POST"])
def export_text():
    """Export reading as a plain text file."""
    data = request.get_json() or {}

    name = data.get("name", "Unknown")
    sun = data.get("sun_sign", "")
    moon = data.get("moon_sign", "")
    rising = data.get("rising_sign", "")
    dob = data.get("dob", "")
    birth_place = data.get("birth_place", "")
    birth_time = data.get("birth_time", "")
    planets = data.get("planets", {})

    lines = [
        "=" * 60,
        "       CELESTIA — YOUR ASTROLOGICAL READING",
        "=" * 60,
        "",
        f"  Name        : {name}",
        f"  Date of Birth : {dob}",
        f"  Birth Time  : {birth_time}",
        f"  Birth Place : {birth_place}",
        "",
        "─" * 60,
        "  THE BIG THREE",
        "─" * 60,
        f"  ☀  Sun Sign    : {sun}",
        f"  🌙 Moon Sign   : {moon}",
        f"  ↑  Rising Sign : {rising}",
        "",
        "─" * 60,
        "  PLANETARY POSITIONS",
        "─" * 60,
    ]

    for planet_name, pdata in planets.items():
        retro = " ℞" if pdata.get("retrograde") else ""
        lines.append(f"  {pdata.get('emoji','★'):<3} {planet_name:<12}: {pdata.get('sign','')}{retro} ({pdata.get('degree','')}°)")

    lines += [
        "",
        "─" * 60,
        "  PERSONALITY",
        "─" * 60,
        data.get("sun_strengths", ""),
        "",
        "─" * 60,
        "  EMOTIONAL WORLD",
        "─" * 60,
        data.get("moon_interpretation", ""),
        "",
        "─" * 60,
        "  YOUR OUTER PRESENCE",
        "─" * 60,
        data.get("rising_interpretation", ""),
        "",
        "─" * 60,
        "  LOVE & RELATIONSHIPS",
        "─" * 60,
        data.get("sun_love", ""),
        "",
        "─" * 60,
        "  CAREER & VOCATION",
        "─" * 60,
        data.get("sun_career", ""),
        "",
        "─" * 60,
        "  LIFE PATH",
        "─" * 60,
        data.get("life_path", ""),
        "",
        "=" * 60,
        "  Generated by Celestia — celestia-astro.onrender.com",
        "=" * 60,
    ]

    content = "\n".join(lines)
    safe_name = re.sub(r"[^\w\s-]", "", name).strip().replace(" ", "_")
    filename = f"celestia_reading_{safe_name}.txt"

    return Response(
        content,
        mimetype="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@app.route("/export/pdf", methods=["POST"])
def export_pdf():
    """Export reading as a styled PDF file."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        Table, TableStyle, HRFlowable)
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        data = request.get_json() or {}
        name = data.get("name", "Unknown")
        sun = data.get("sun_sign", "")
        moon = data.get("moon_sign", "")
        rising = data.get("rising_sign", "")
        dob = data.get("dob", "")
        birth_place = data.get("birth_place", "")
        birth_time = data.get("birth_time", "")
        planets = data.get("planets", {})

        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                rightMargin=2*cm, leftMargin=2*cm,
                                topMargin=2*cm, bottomMargin=2*cm)

        # Colors
        DARK_BG = colors.HexColor("#0D0D1A")
        GOLD = colors.HexColor("#C9A84C")
        PURPLE = colors.HexColor("#8B5CF6")
        LIGHT = colors.HexColor("#E2D9F3")
        WHITE = colors.white

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("title", fontSize=24, textColor=GOLD,
                                     alignment=TA_CENTER, spaceAfter=6,
                                     fontName="Helvetica-Bold")
        subtitle_style = ParagraphStyle("subtitle", fontSize=12, textColor=LIGHT,
                                        alignment=TA_CENTER, spaceAfter=20)
        heading_style = ParagraphStyle("heading", fontSize=14, textColor=GOLD,
                                       spaceAfter=8, spaceBefore=16,
                                       fontName="Helvetica-Bold")
        body_style = ParagraphStyle("body", fontSize=10, textColor=LIGHT,
                                    spaceAfter=10, leading=16)
        label_style = ParagraphStyle("label", fontSize=10, textColor=GOLD,
                                     fontName="Helvetica-Bold")

        story = []

        # Title
        story.append(Paragraph("✦ CELESTIA ✦", title_style))
        story.append(Paragraph("Your Astrological Reading", subtitle_style))
        story.append(HRFlowable(width="100%", color=GOLD, thickness=1))
        story.append(Spacer(1, 0.5*cm))

        # Birth Data
        story.append(Paragraph("BIRTH INFORMATION", heading_style))
        birth_data = [
            ["Name", name],
            ["Date of Birth", dob],
            ["Birth Time", birth_time],
            ["Birth Place", birth_place],
        ]
        t = Table(birth_data, colWidths=[4*cm, 13*cm])
        t.setStyle(TableStyle([
            ("TEXTCOLOR", (0, 0), (0, -1), GOLD),
            ("TEXTCOLOR", (1, 0), (1, -1), LIGHT),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#1A1A2E"), colors.HexColor("#16213E")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#2D2D5E")),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.5*cm))

        # Big Three
        story.append(Paragraph("THE BIG THREE", heading_style))
        big3 = [
            ["☀  Sun Sign", sun],
            ["🌙 Moon Sign", moon],
            ["↑  Rising Sign", rising],
        ]
        t2 = Table(big3, colWidths=[5*cm, 12*cm])
        t2.setStyle(TableStyle([
            ("TEXTCOLOR", (0, 0), (0, -1), GOLD),
            ("TEXTCOLOR", (1, 0), (1, -1), LIGHT),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 11),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#1A0533"), colors.HexColor("#1A1A2E")]),
            ("GRID", (0, 0), (-1, -1), 0.5, PURPLE),
            ("PADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(t2)

        # Sections
        sections = [
            ("PERSONALITY", data.get("sun_strengths", "")),
            ("YOUR CHALLENGES", data.get("sun_challenges", "")),
            ("EMOTIONAL WORLD", data.get("moon_interpretation", "")),
            ("YOUR OUTER PRESENCE", data.get("rising_interpretation", "")),
            ("LOVE & RELATIONSHIPS", data.get("sun_love", "")),
            ("CAREER & VOCATION", data.get("sun_career", "")),
            ("LIFE PATH", data.get("life_path", "")),
        ]
        for sec_title, sec_text in sections:
            if sec_text:
                story.append(Paragraph(sec_title, heading_style))
                story.append(Paragraph(sec_text, body_style))

        # Planets table
        if planets:
            story.append(Paragraph("PLANETARY POSITIONS", heading_style))
            planet_rows = [["Planet", "Sign", "Degree", "Element"]]
            for pname, pdata in planets.items():
                retro = " ℞" if pdata.get("retrograde") else ""
                planet_rows.append([
                    f"{pdata.get('emoji','★')} {pname}",
                    f"{pdata.get('sign','')}{retro}",
                    f"{pdata.get('degree','')}°",
                    pdata.get("element", "")
                ])
            t3 = Table(planet_rows, colWidths=[5*cm, 5*cm, 3*cm, 4*cm])
            t3.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2D1B69")),
                ("TEXTCOLOR", (0, 0), (-1, 0), GOLD),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("TEXTCOLOR", (0, 1), (-1, -1), LIGHT),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#1A1A2E"), colors.HexColor("#16213E")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#2D2D5E")),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("PADDING", (0, 0), (-1, -1), 7),
            ]))
            story.append(t3)

        # Footer
        story.append(Spacer(1, cm))
        story.append(HRFlowable(width="100%", color=GOLD, thickness=0.5))
        story.append(Paragraph("Generated by Celestia — Your Premium Astrology Experience",
                                ParagraphStyle("footer", fontSize=8, textColor=GOLD,
                                               alignment=TA_CENTER, spaceBefore=6)))

        doc.build(story)
        buffer.seek(0)

        safe_name = re.sub(r"[^\w\s-]", "", name).strip().replace(" ", "_")
        filename = f"celestia_reading_{safe_name}.pdf"

        return Response(
            buffer.read(),
            mimetype="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )

    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
